### ISSUE TITLE
LOOP-END bug?

### ISSUE THREAD

**Issue by ghost** [k-john-gough/gpcp#7]
```
MODULE FailTest;

  IMPORT CPmain;

BEGIN
  LOOP END
END FailTest.
```
```
deaddoomer@sun otc $ gpcp -version FailTest.cp
#gpcp: jvm version 1.4.04 of 07 August 2017
#gpcp: Using AsmUtil - default (V1_7) emitter
#gpcp: <FailTest> No errors
deaddoomer@sun otc $ cprun FailTest
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.VerifyError: Expecting a stack map frame
Exception Details:
  Location:
    CP/FailTest/FailTest.main([Ljava/lang/String;)V @8: return
  Reason:
    Error exists in the bytecode
  Bytecode:
    0x0000000: 2ab8 0013 00a7 ffff b1                 
  Stackmap Table:
    same_frame(@4)

	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
deaddoomer@sun otc $ java -version
openjdk version "1.8.0_144"
OpenJDK Runtime Environment (IcedTea 3.5.1) (CRUX)
OpenJDK 64-Bit Server VM (build 25.144-b01, mixed mode)
```

With -asm5, -asm6 or -legacy everythin ok.

**Comment by k-john-gough** [comment]
This error is caused by a program module body ending with an endless loop. GPCP, by default, puts a return on the bytecodes anyway. This breaks if the JVM is expecting stack frames for verification, that is, for SE 7+. The problem is because no code path leads to the return there is no valid stack frame possible.

I have a fix for this, but am trying to fix all three issues raised by DeaDDooMER with one commit.
